version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app  # Maps the local frontend directory to the container
    ports:
      - "3000:80"  # Set the port directly
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:5001

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app  # Maps the local backend directory to the container
    ports:
      - "5001:5001"  # Set the port directly
    networks:
      - app-network
    environment:
      - FLASK_ENV=development  # Set the environment to development
      - DATABASE_URL=postgresql://abdelnasser:greatness@db:5432/mydatabase  # Connection string for PostgreSQL
      - DEV_DATABASE_URL=postgresql://abdelnasser:greatness@db:5432/mydatabase  # For development config
      - TEST_DATABASE_URL=postgresql://abdelnasser:greatness@db:5432/mydatabase_test  # For testing config

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: abdelnasser
      POSTGRES_PASSWORD: greatness
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
