# Dockerfile.test

FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir requests pytest

COPY . .

CMD ["pytest"]
